name: HIFINI-Auto-Checkin

on:
  workflow_dispatch:          # 允许手动触发
  schedule:                   # 定时触发
    - cron: '00 16 * * *'     
      
jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    environment: HIFINI
    env:
      COOKIE: ${{ secrets.COOKIE }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest.
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkin
        shell: bash
        run: |
          node main.js
